Add 2 sections : Scilla Videos, Magic integration; Updated ZRC2 section
Zilliqa/dev-portal-old pull request #120
Opened 2020-12-02 08:42 UTC by arnavvohra

2020-12-08 09:26 UTC, ansnunez approved these changes

2020-12-10 09:21 UTC, bb111189 requested changes

2020-12-10 09:21 UTC, bb111189 commented on docs/dev/dev-keys-zrc2-wallet-support.mdx
> +Token allowance allows the dApp contract to transfer ZRC-2 token, if the current approved allowance is less than `amount`.  If the allowance is sufficient, this method is a no-op. The approval is don
Token allowance allows the dApp contract to transfer ZRC-2 token, if the current approved allowance is less than `amount`

@arnavvohra  should it be equal or more than?

2020-12-10 09:21 UTC, bb111189 commented on docs/dev/dev-keys-zrc2-wallet-support.mdx
> +In the example below the allowance amount is the same as the entire token supply. This is done so that the approval needs to only be done once per token contract, reducing the number of approval tran
```suggestion
In the example below. the allowance amount is the same as the entire token supply. This is done so that the approval needs to only be done once per token contract, reducing the number of approval transactions required for users conducting multiple swaps. 
```

2020-12-10 09:21 UTC, bb111189 commented on docs/dev/dev-keys-zrc2-wallet-support.mdx
> +TransferFrom transition moves a given amount of tokens from one address to another using the allowance mechanism.
```suggestion
`TransferFrom` transition moves a given amount of tokens from one address to another using the allowance mechanism. 
```

2020-12-10 09:21 UTC, bb111189 commented on docs/dev/dev-keys-zrc2-wallet-support.mdx
> +Token allowance allows the dApp contract to transfer ZRC-2 token, if the current approved allowance is less than `amount`.  If the allowance is sufficient, this method is a no-op. The approval is don
Can we add a subsection, explanation the purpose and rationale of allowance and why is it important?

2020-12-10 09:21 UTC, bb111189 commented on docs/dev/dev-keys-zrc2-wallet-support.mdx
> +In a ZRC-2 fungible tokens contract, the mutable field `total_supply` stores the value of the current total supply.
Can you explain that the input is the contract address? People may not know what is `173Ca6770Aa56EB00511Dac8e6E13B3D7f16a5a5`

2020-12-10 09:21 UTC, bb111189 commented on docs/dev/dev-keys-zrc2-wallet-support.mdx
> +## Tracking Incoming ZRC-2 Deposit
This section is a copy and paste of my exchange section right? Rather than copying and pasting, which make it hard to maintain and become inconsistent, can you reference the page instead?

2020-12-10 09:21 UTC, bb111189 commented on docs/dev/dev-keys-zrc2-wallet-support.mdx
> +## Tracking Incoming ZRC-2 Deposit
It is written very very specific to exchange and assume exchange infrastructure. I don't think it is wise to copy and paste it in full

2021-01-04 04:42 UTC, bb111189 requested changes

2021-01-04 04:42 UTC, bb111189 commented on docs/dev/dev-education-videos.mdx
> +description: Zilliqa and Scilla Development Videos - Write smart contracts and build dapps.
```suggestion
description: Zilliqa and Scilla Development Videos - Write smart contracts and build DApps.
```

2021-01-04 04:43 UTC, bb111189 approved these changes

2021-01-04 06:22 UTC, merged