v1 ceres documentation
Zilliqa/dev-portal-old pull request #126
Opened 2020-12-15 11:57 UTC by arnavvohra

2020-12-15 14:53 UTC, bb111189 requested changes

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +Ceres is a one-stop development application for developers looking to build on top of zilliqa.
```suggestion
Ceres is a one-stop development application for developers looking to build on top of Zilliqa. 
```

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +It is a simple to use graphical interface that has multiple zilliqa development tools.
```suggestion
It is a simple to use graphical interface that has multiple Zilliqa development tools. 
```

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +## Available Services
```suggestion

## Available Services
```

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +1. Server Container (http://localhost:5555) is the local zilliqa blockchain network and it comes with 10 accounts.
```suggestion
1. Server Container (http://localhost:5555) is the local Zilliqa blockchain network and it comes with 10 pre-loaded accounts.
```

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +Also, you would need to change the Chain Id to reflect the value relevant for the isolated server i.e. 222.
```suggestion
Also, you would need to change the Chain ID to reflect the value relevant for the isolated server i.e. 222. 
```

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +isolated server. Network Explorer runs on the port 5557. You can access it from any browser on http://localhost:5557.
```suggestion
isolated server. Devex runs on the port 5557. You can access it from any browser on http://localhost:5557.
```

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +Step 1 : Visit ide.zilliqa.com and start a new file. In this file, paste the code for the fungible token contract (zrc2 contract)
Don't ask the user to go to a site, to paste code to another site. This is very unfriendly

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +know about the id of your zilliqa network.
```suggestion
know about the id of your Zilliqa network.
```

2020-12-15 14:53 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +Step 6: You can click on the transaction id link and you will be redirected to Devex page, alternatively you can also visit http://localhost:5557 (local network explorer) and you will find your contr
```suggestion
Step 6: You can click on the transaction ID link and you will be redirected to Devex page, alternatively you can also visit http://localhost:5557 (local network explorer) and you will find your contract creation transaction there as well.
```

2020-12-15 14:59 UTC, bb111189 requested changes

2020-12-15 14:59 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +To interact with the local blockchain network with your dapp, you would need to set the value of the RPC server URL when
```suggestion
To interact with the local blockchain network with your dApp, you would need to set the value of the RPC server URL when
```

2020-12-15 14:59 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +In this section, we will deploy a fungible token smart contract using the Zilliqa IDE which would be connected to your
```suggestion
In this section, we will deploy a fungible token (ZRC-2) smart contract using the Zilliqa IDE which would be connected to your 
```

2020-12-15 14:59 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +After you are done with installation of Ceres and all the available services, you can start using ceres for your dapp development.
```suggestion
After you are done with installation of Ceres and all the available services, you can start using Ceres for your dApp development.
```

2020-12-15 14:59 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +Step 1 : Visit ide.zilliqa.com and start a new file. In this file, paste the code for the fungible token contract (zrc2 contract)
Hyperlink the IDE

2020-12-15 14:59 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +Step 3: Select an account that you will eventually use to deploy the contract. In this example, we are using a keystore file but you can use ledger or zilpay, which is zilliqa wallet available as a c
```suggestion
Step 3: Select an account that you will eventually use to deploy the contract. In this example, we are using a keystore file but you can use ledger or Zilpay, which is Zilliqa wallet available as a chrome extension similar to metamask.
```

2020-12-15 15:00 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +description: Zilliqa Testnet Faucet
This description is wrong

2020-12-15 15:00 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +Development tools that come with Ceres currently are isolated server, Devex developer block explorer and scilla server.
```suggestion
Development tools that come with Ceres currently are isolated server, Devex developer block explorer and Scilla server. 
```

2020-12-15 15:01 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +Ceres is a one-stop development application for developers looking to build on top of zilliqa.
```suggestion
Ceres is a one-stop local development application for developers looking to build on top of zilliqa. 
```

2020-12-15 15:06 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +- nucleus wallet
There is no nucleus wallet

2020-12-15 15:08 UTC, bb111189 commented on docs/dev/dev-tools-ceres.mdx
> +More details about Scilla Server can be found [here](https://github.com/zilliqa/scilla-server).
The github is a private repo

2020-12-16 07:27 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +Development tools that come with Ceres currently are isolated server, Devex developer block explorer and Scilla server.
Can we hyper link `Isolated server`, `Devex` and `Scilla server` to the sections that explain them?

2020-12-16 07:28 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +Ports 5555, 5556 for Isolated Server
Use bullet points.

2020-12-16 07:31 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +Ceres allows developers to run these tools locally on their machine which allows them to: run a local zilliqa blockchain network,
```suggestion
Ceres allows developers to run these tools locally on their machine which allows them to: run a local Zilliqa blockchain network,
```

2020-12-16 07:34 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +The scilla-server process accepts contract execution requests and executes the contract, providing a JSON output within the
```suggestion
The scilla-server accepts contract execution requests and executes them, providing a JSON output within the
```

2020-12-16 07:35 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +After downloading is finished, you need to click on to Start Service - you have now successfully started the scilla server.
```suggestion
After downloading is finished, you need to click on to Start Service - you have now successfully started the Scilla server.
```

2020-12-16 07:35 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +Scilla server runs scilla binaries locally and exposes API endpoints for the scilla-checker and scilla-runner.
```suggestion
Scilla server runs Scilla binaries locally and exposes API endpoints for `scilla-checker` and `scilla-runner`. 
```

2020-12-16 07:36 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +The scilla-server provides the functionality of scilla-runner and scilla-checker as a JSON-RPC server.
```suggestion
Scilla server provides the functionality of `scilla-runner` and `scilla-checker` as a JSON-RPC server.
```

2020-12-16 07:37 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +To start the scilla server, you need to click on “Scilla” from the Ceres’ home screen and then click on “Download and install”.
```suggestion
To start the server, you need to click on “Scilla” from the Ceres’ home screen and then click on “Download and install”.
```

2020-12-16 07:37 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +After downloading is finished, you need to click on to Start Service - you have now successfully started the scilla server.
```suggestion
After downloading is finished, you need to click on to Start Service - you have now successfully started the Scilla server.
```

2020-12-16 07:38 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +local zilliqa blockchain network. We will also use the local faucet & network explorer in the process.
```suggestion
local Zilliqa blockchain network. We will also use the local faucet & network explorer in the process. 
```

2020-12-16 07:39 UTC, AmritKumar commented on docs/dev/dev-tools-ceres.mdx
> +Step 3: Select an account that you will eventually use to deploy the contract. In this example, we are using a keystore file but you can use ledger or Zilpay, which is Zilliqa wallet available as a c
```suggestion
Step 3: Select an account that you will eventually use to deploy the contract. In this example, we are using a keystore file but you can use ledger or Zilpay, which is a Zilliqa wallet available as a chrome extension similar to metamask.
```

2020-12-16 07:41 UTC, AmritKumar requested changes
Some minor editorial changes.

2020-12-17 09:26 UTC, bb111189 approved these changes

2020-12-22 09:07 UTC, AmritKumar approved these changes

2020-12-22 10:38 UTC, merged