Create wrapped tokens page
Zilliqa/dev-portal-old pull request #208
Opened 2021-10-05 17:29 UTC by Elliott-Green

Created a page with infomation about wrapped zil. 
Discussed what it is, how to use it and why it might be used.

2021-10-05 17:30 UTC, Elliott-Green commented
build is currently 429ing but does compile correctly and works locally.

2021-10-07 04:27 UTC, bb111189 requested changes

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +  - wbtc
remove wbtc and weth

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +The wZil contract exposes ZRC-2 compliant transitions names. Users are able to call "Mint" with an amount of ZIL, LI or QA and have an equal amount of wZIL returned to them. Similarly when calling "B
For this section,. mention that with wZIL, users can 
- Mention that anyone can get convert ZIL to wZIL in a trustless manner via a smart contract 
- call transition such as `transfer` which is not available in the native ZIL token
- This can simplify smart contracts as developers no need to support both native ZIL token and  ZRC-2


Move the burning and minting to another section. "How to get wZIL" and  "How to  get back ZIL"

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +## wZIL
change to motivation of wZIL

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +The standard naming convention of non native wrapped assets on Zilliqa is "zW". Developers may choose to consume wZIL instead of ZIL in their smart contracts as it already provides standard ZRC-2 tra
the z convention is for bridged token not token. Can remove this para

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +## Wrapped Tokens
I think we can just straight to motivation of wZIL. I think this paragraph might not be neccessary

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +![Docusaurus](/img/dev/wzil/pillar_wzil.png)
broken link

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +Users may choose to manually wrap or unwrap ZIL manually from the wrapper contract. To wrap or unwrap tokens, firstly import the wZIL contract to the IDE.
Add a new section title. Interacting with the wZIL contract with the Neo-savant IDE

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +title: Wrapped Tokens
Change to Wrapped ZIL

2021-10-07 04:27 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +id: dev-wrapped-tokens
change to dev-wrapped-zil

2021-10-07 04:30 UTC, bb111189 requested changes

2021-10-07 04:30 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +<br />
no need for <br/> for this markdown. Let markdown handle it. If needed, use doublespace for new line

2021-10-07 04:30 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +<b>  </b>
unused tag?

2021-10-07 04:30 UTC, bb111189 commented on docs/dev/dev-wrapped-tokens.md
> +<hr />
no need for horizontal line. Let markdown section header divide the page

2021-10-14 04:49 UTC, bb111189 approved these changes

2021-10-14 04:49 UTC, merged