Update exchange section documentation update
Zilliqa/dev-portal-old pull request #224
Opened 2022-01-18 08:17 UTC by chetan-zilliqa

2022-01-18 08:18 UTC, ansnunez approved these changes

2022-01-25 03:46 UTC, sandipbhoir requested changes

2022-01-25 03:46 UTC, sandipbhoir commented on docs/exchanges/exchange-ip-whitelisting.md
> +Enter your IP address (*.*.*.*): <static ip address>
need to update to `Enter your public IP address` after PR https://github.com/Zilliqa/testnet/pull/947.
Similarly for all rest of files.

2022-01-25 03:48 UTC, chetan-zilliqa commented on docs/exchanges/exchange-ip-whitelisting.md
> +Enter your IP address (*.*.*.*): <static ip address>
This actually refers to the current implementation, `Enter your public IP address` instruction is not yet live, so haven't been updated.
I will update this doc again when we push the new tarballs.

2022-01-25 03:58 UTC, sandipbhoir approved these changes

2022-01-28 14:09 UTC, merged