Add pending Transaction
Zilliqa/dev-portal-old pull request #31
Opened 2019-12-09 06:29 UTC by KaustubhShamshery

2019-12-10 03:14 UTC, bb111189 commented
rename the file with the prefix `api-`

2019-12-10 03:14 UTC, ansnunez commented on docs/pending-txn.md
> +The shard nodes, at the end of every epoch send the lookup nodes infomration about transactions pending in their pool.
```suggestion
At the end of every Tx epoch, lookup nodes receive information from the shards about pending (i.e., unconfirmed) transactions in their transaction pool. This information is accessible through the API at the lookup nodes, and is refreshed once the latest Tx block is available.
```

2019-12-10 03:15 UTC, ansnunez commented on docs/pending-txn.md
> +Example:
```suggestion
## Example
```

2019-12-10 03:21 UTC, bb111189 requested changes
As this is public documentation, we will need to ensure our documentation is professional. This is to ensure user can follow through the documentation without getting confused.

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +
Add `This page describes .....`

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +# Pending Txn API
Remove this line

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +5. WHAT THE API DOES NOT DO : It would not tell if a txn is dropped.
rephrase this

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +```
@renlulu  possible to provide some example using sdk?

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +1. Nonce too high : if in a shard’s mempool a txn is pending which has a nonce greater than the current nonce of the account.
txn -> transaction

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +2. Gas Limit Exceeded : if the txn in the mempool wasnt able to fit in the current MB due to limit being exceeded, it would show this error
txn -> transaction
MB -> microblock

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +2. Gas Limit Exceeded : if the txn in the mempool wasnt able to fit in the current MB due to limit being exceeded, it would show this error
limit -> gas limit

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +2. Gas Limit Exceeded : if the txn in the mempool wasnt able to fit in the current MB due to limit being exceeded, it would show this error
rephrase so that it is not so casual. The last part of the sentence

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +3. Correct but consensus failure : for some reason if MB was not made and the txn still resides in the mempool, this would be reported.
What do you mean by `correct`? The reader may not be aware of it. 
`Transaction not processed due to failure in consensus`

2019-12-10 03:21 UTC, bb111189 commented on docs/pending-txn.md
> +3. Correct but consensus failure : for some reason if MB was not made and the txn still resides in the mempool, this would be reported.
txn -> transaction

2019-12-10 03:23 UTC, ansnunez commented on docs/pending-txn.md
> +4. Shard nodes send a packet to the lookup nodes, This contains the txn hash and a code which tells why the txn is pending.
Err it says there are 3 types but you have 5 bullet points

2019-12-10 03:23 UTC, ansnunez commented on docs/pending-txn.md
> +Three types of pending txns would be reported
Probably make this into a separate subsection after Introduction

2019-12-10 03:24 UTC, ansnunez commented on docs/pending-txn.md
> +2. Gas Limit Exceeded : if the txn in the mempool wasnt able to fit in the current MB due to limit being exceeded, it would show this error
Better to put the actual strings reported. In this case it is `Could not fit in as microblock gas limit reached` I believe

2019-12-10 03:24 UTC, ansnunez commented on docs/pending-txn.md
> +3. Correct but consensus failure : for some reason if MB was not made and the txn still resides in the mempool, this would be reported.
I don't actually see this status returned in `StatusServer::IsTxnInMemPool`

2019-12-10 03:25 UTC, ansnunez commented on docs/pending-txn.md
> +4. Shard nodes send a packet to the lookup nodes, This contains the txn hash and a code which tells why the txn is pending.
Just remove #4 I think.  And add the `NOT_PRESENT` case as well.

2019-12-10 03:25 UTC, ansnunez commented on docs/pending-txn.md
> +5. WHAT THE API DOES NOT DO : It would not tell if a txn is dropped.
Maybe put this as a separate subsection "Limitations"

2019-12-10 03:26 UTC, ansnunez commented on docs/pending-txn.md
> +# Pending Txn API
Inconsistency between lines 3 and 6.  I prefer "Pending Transaction API"

2019-12-10 06:46 UTC, ansnunez requested changes

2019-12-10 06:46 UTC, ansnunez commented on docs/api-pending-txn.md
> +4. Not Present : The transaction hash being quried is not pending.
```suggestion
4. `Txn not pending`: the transaction being queried is not pending (i.e., it does not exist in the transaction pool).
```

2019-12-10 06:46 UTC, ansnunez commented on docs/api-pending-txn.md
> +1. Nonce too high : if in a shard’s mempool a transaction is pending which has a nonce greater than the current nonce of the account.
```suggestion
1. `Nonce too high`: the transaction is pending because its nonce is larger than expected.
```

2019-12-10 06:46 UTC, ansnunez commented on docs/api-pending-txn.md
> +2. Could not fit in as microblock gas limit reached : if the transaction in the mempool wasn't able to fit in the current microblock due to current gas limit being exceeded.
```suggestion
2. `Could not fit in as microblock gas limit reached`: the transaction is pending because it would cause the microblock to exceed the current gas limit.
```

2019-12-10 06:46 UTC, ansnunez commented on docs/api-pending-txn.md
> +3. Transaction valid but consensus not reached : Due to consensus failure at shard or DS level, this transaction is pending.
```suggestion
3. `Transaction valid but consensus not reached`: the transaction is pending due to consensus failure within the network.
```

2019-12-10 06:46 UTC, ansnunez commented on docs/api-pending-txn.md
> +Three types of pending transactions would be reported
```suggestion
These are the types of responses that are reported by the API.
```

2019-12-10 06:46 UTC, ansnunez commented on docs/api-pending-txn.md
> +## Usage
Added some suggestions for each item below.
For easier readability, each bullet point begins with "the transaction is pending because...".
Also, the report string is formatted so people know it's a literal string that is spit out by the lookup.

2019-12-10 06:46 UTC, ansnunez commented on docs/api-pending-txn.md
> +The API would only tell if a transaction is pending or not. It cannot tell if it is dropped.
```suggestion
This API relies on the contents of the transaction pool and can therefore only indicate whether a transaction is pending or not (for the reasons listed above). As such, it cannot be used to determine if a transaction was processed and intentionally dropped or rejected by the network.
```

2019-12-12 04:27 UTC, bb111189 approved these changes

2019-12-12 04:27 UTC, merged