Added exchange-transaction-receipts.md
Zilliqa/dev-portal-old pull request #64
Opened 2020-06-19 04:44 UTC by ansnunez

2020-06-22 03:06 UTC, bb111189 requested changes

2020-06-22 03:06 UTC, bb111189 commented on docs/exchange-transaction-receipts.md
> +For contract transactions, more information is contained in additional fields under the "**receipt**".
```suggestion
For smart contract transactions, additional information relating to smart contract execution is contained in additional fields under the "**receipt**".
```

2020-06-22 03:06 UTC, bb111189 commented on docs/exchange-transaction-receipts.md
> +| **accepted**       | boolean    | Indicates whether the last transition in this transaction incurred a balance transfer        |
```suggestion
| **accepted**       | boolean    | Indicates whether the last transition in this transaction incurred a **balance transfer**        |
```

2020-06-22 03:06 UTC, bb111189 commented on docs/exchange-transaction-receipts.md
> +If a transaction is unsuccessful (i.e., the **success** field is `false`), these fields will be present:
```suggestion
If a transaction is unsuccessful (i.e., the **success** field is `false`) and no balance transfer will be executed.

These fields will be present:
```

2020-06-22 03:06 UTC, bb111189 commented on docs/exchange-transaction-receipts.md
> +   1. Check whether the **_tag** in the contract is a transition that performs a balance transfer
If it doesn't not allow balance transfer, success is false right?

2020-06-22 03:06 UTC, bb111189 commented on docs/exchange-transaction-receipts.md
> +## Multiple Transitions with Balance Transfers
Another new section
## Recommendation for exchanges polling for incoming deposit from smart contract transactions
1. Confirm that the **success** field is set to `true`
1. Traverse the **transitions** JSON array. For each transition, for a successful deposit of `$ZIL` via the smart contract, the following must be fulfilled:
   1. If the `_recipient` corresponds to a known exchange deposit address you controlled
   1. ` _tag` is either `AddFunds` or empty
   1. `_amount` is non zero
In such a case, you can confirm that there is a deposit to address `_recipient` with value `_amount` (in `Qa`). 
1. Continue on the traversing and to check for more deposits


@kaikawaliu

2020-06-22 03:10 UTC, bb111189 commented on docs/exchange-transaction-receipts.md
> +## Multiple Transitions with Balance Transfers
For `Multiple Transitions with Balance Transfers`, I suggest we put it in our upcoming revamp of dev portal instead, so as to not confuse exchanges

2020-06-23 02:33 UTC, bb111189 approved these changes

2020-06-23 02:52 UTC, kaikawaliu approved these changes

2020-06-23 03:09 UTC, kaikawaliu commented on docs/exchange-transaction-receipts.md
> +## Multiple Transitions with Balance Transfers
I suggest to check the `_tag` first since it's an easier search comparing to looking up the `_recipient`

2020-06-23 04:14 UTC, merged